theme: jekyll-theme-minimal
title: SCOPE
description: "Social Construction of Protest and its Effects: Media depictions and Public Attitudes towards Protest in Spain in comparative perspective (SCOPE)"
logo: logo_no_title.jpg
show_downloads: false
baseurl: "/SCOPE"
